version: '3'
services:
    nginx:
      image: nginx
      container_name: "test-nginx"
      ports:
        - "5000:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./src:/src
      links:
        - php
    php:
        image: ray1101/php-custom
        container_name: "test-php"
        expose:
            - "9000"
        volumes:
            - ./src:/src
        links:
            - mariadb
    mariadb:
        image: mariadb:10.3.10
        container_name: "test-mariadb"
        environment:
            MYSQL_DATABASE: ${USER}
            MYSQL_ROOT_PASSWORD: ${PASS}
        volumes:
            -  ./db:/var/lib/mariadb
        expose:
            - "8000"
